apiVersion: apps/v1
kind: Deployment
metadata:
  name: ankush
  labels:
    app: ankush
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: ankush
  template:
    metadata:
      labels:
        app: ankush
    spec:    
      containers:
      - name: ankush
        image: ankushsatpute/ankush:tagVersion
        imagePullPolicy: Always      
        ports:
        - containerPort: 8080
